name: publish-actions
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install and build
        run: |
          npm install 
          npm run build -- --base=/kaossilator/
      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "Benjamin Legrand" && git config user.email "benjilegnard@users.noreply.github.com"
          npm run deploy -- --repo https://benjilegnard:${{ secrets.GITHUB_TOKEN }}@github.com/gotloop/kaossilator.git --message "updates from ${GITHUB_SHA}" --no-history
