name: publish-actions
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Install and build
        run: |
          pnpm install 
          pnpm run build --base=/kaossilator/
      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "Benjamin Legrand" && git config user.email "benjilegnard@users.noreply.github.com"
          pnpm run deploy --repo https://benjilegnard:${{ secrets.GITHUB_TOKEN }}@github.com/gotloop/kaossilator.git --message "updates from ${GITHUB_SHA}" --no-history
